#  ________  ________  ___  ___  ___       __   ________  ________  ___  ___
# |\   __  \|\   __  \|\  \|\  \|\  \     |\  \|\   __  \|\   __  \|\  \|\  \
# \ \  \|\  \ \  \|\ /\ \  \\\  \ \  \    \ \  \ \  \|\  \ \  \|\ /\ \  \\\  \
#  \ \   __  \ \   __  \ \  \\\  \ \  \  __\ \  \ \   __  \ \   __  \ \  \\\  \
#   \ \  \ \  \ \  \|\  \ \  \\\  \ \  \|\__\_\  \ \  \ \  \ \  \|\  \ \  \\\  \
#    \ \__\ \__\ \_______\ \_______\ \____________\ \__\ \__\ \_______\ \_______\
#     \|__|\|__|\|_______|\|_______|\|____________|\|__|\|__|\|_______|\|_______|

#  Filename: config.toml


theme = "tokyonight"

[editor]
true-color = true
line-number = "relative"
cursorline = true
color-modes = true
rulers = [90]

[editor.cursor-shape]
select = "underline"
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["diagnostics"]
right = ["selections", "position", "file-encoding", "file-type"]

[editor.lsp]
display-messages = true
