#  ________  ________  ___  ___  ___       __   ________  ________  ___  ___
# |\   __  \|\   __  \|\  \|\  \|\  \     |\  \|\   __  \|\   __  \|\  \|\  \
# \ \  \|\  \ \  \|\ /\ \  \\\  \ \  \    \ \  \ \  \|\  \ \  \|\ /\ \  \\\  \
#  \ \   __  \ \   __  \ \  \\\  \ \  \  __\ \  \ \   __  \ \   __  \ \  \\\  \
#   \ \  \ \  \ \  \|\  \ \  \\\  \ \  \|\__\_\  \ \  \ \  \ \  \|\  \ \  \\\  \
#    \ \__\ \__\ \_______\ \_______\ \____________\ \__\ \__\ \_______\ \_______\
#     \|__|\|__|\|_______|\|_______|\|____________|\|__|\|__|\|_______|\|_______|

#  Filename: config.toml


theme = "tokyonight"

[editor]
true-color = true
line-number = "relative"
cursorline = true
color-modes = true
rulers = [80]
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer"]

[editor.cursor-shape]
select = "underline"
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "file-type", "file-encoding"]
right = ["selections", "position", "position-percentage"]

[editor.lsp]
display-messages = true
auto-signature-help = false
display-signature-help-docs = false

[keys.insert]
C-p = "signature_help"

[keys.normal]
c = ["trim_selections", "change_selection"]
C-d = ["half_page_down", "align_view_center"]
C-u = ["half_page_up", "align_view_center"]
C-b = ["page_up", "align_view_center"]
C-f = ["page_down", "align_view_center"]
