#  ________  ________  ___  ___  ___       __   ________  ________  ___  ___
# |\   __  \|\   __  \|\  \|\  \|\  \     |\  \|\   __  \|\   __  \|\  \|\  \
# \ \  \|\  \ \  \|\ /\ \  \\\  \ \  \    \ \  \ \  \|\  \ \  \|\ /\ \  \\\  \
#  \ \   __  \ \   __  \ \  \\\  \ \  \  __\ \  \ \   __  \ \   __  \ \  \\\  \
#   \ \  \ \  \ \  \|\  \ \  \\\  \ \  \|\__\_\  \ \  \ \  \ \  \|\  \ \  \\\  \
#    \ \__\ \__\ \_______\ \_______\ \____________\ \__\ \__\ \_______\ \_______\
#     \|__|\|__|\|_______|\|_______|\|____________|\|__|\|__|\|_______|\|_______|

#  Filename: config.toml


theme = "tokyonight"

[editor]
true-color = true
line-number = "relative"
cursorline = true
color-modes = true
rulers = [80]
gutters = ["diagnostics", "line-numbers", "spacer"]
bufferline = "always"

[editor.cursor-shape]
select = "underline"
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "file-type", "file-encoding"]
right = ["selections", "position", "position-percentage"]

[editor.lsp]
display-messages = true
auto-signature-help = false
display-signature-help-docs = false
